[package]
name = "rust2prod_amir"
version = "0.1.0"
edition = "2021"


authors = ["Amir Alesheikh <amirhossein.alesheikh@gmail.com>"]

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rust2prod_amir"

[dependencies]
axum = "0.6.0"
serde = { version = "1.0.148", features = ["derive"] }
tokio = { version = "1.22.0", features = ["rt-multi-thread", "tokio-macros", "macros"] }

[dev-dependencies]
reqwest = { version = "0.11.13", default-features = false, features = ["rustls-tls" ] }
